name: daily_awe
description: A Flutter app that delivers awe-inspiring visual experiences powered by Pexels.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  introduction_screen: ^3.1.12
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1A1A1A" # Matches our dark theme background
  adaptive_icon_foreground: "assets/icons/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/audio/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          style: normal
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700 